### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lynch0x** [MSPRetro/client#2]
So my question is why did you put the source code of checksum creation public. Like what’s the reason for all of it? Why have you added checksum in the first place if you leaked it now?

**Comment by cy-polo** [comment]
Hi,

this checksum isn't a real security. It's very easy to obtain it and understand how to send your own requests.

Too many people think that MSPRetro contains a virus. I'm proving the opposite by publishing the source code.
This will allow anyone to compile the application easily.

Best
